name: Deploy

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  DevTests:
    uses: ./.github/workflows/testing_dev.yml
    secrets:
      IP_HASH_SALT: ${{ secrets.IP_HASH_SALT }}
      IPINFO_CREDENTIALS: ${{ secrets.IPINFO_CREDENTIALS }}
      CODECOV_CREDENTIALS: ${{ secrets.CODECOV_CREDENTIALS }}
