name: Deploy

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  Tests:
    uses: ./.github/workflows/testing.yml
    secrets:
      S3_LOG_EXTRACTION_PASSWORD: ${{ secrets.S3_LOG_EXTRACTION_PASSWORD }}
      CODECOV_CREDENTIALS: ${{ secrets.CODECOV_CREDENTIALS }}

  RemoteTests:
      uses: ./.github/workflows/remote_testing.yml
      secrets:
          S3_LOG_EXTRACTION_PASSWORD: ${{ secrets.S3_LOG_EXTRACTION_PASSWORD }}
          MAXMIND_ACCOUNT_ID: ${{ secrets.MAXMIND_ACCOUNT_ID }}
          MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
          OPENCAGE_API_KEY: ${{ secrets.OPENCAGE_API_KEY }}
          CODECOV_CREDENTIALS: ${{ secrets.CODECOV_CREDENTIALS }}
