name: Remote testing
on:
  workflow_call:
    secrets:
      S3_LOG_EXTRACTION_PASSWORD:
        required: true
      MAXMIND_ACCOUNT_ID:
        required: true
      MAXMIND_LICENSE_KEY:
        required: true
      CODECOV_CREDENTIALS:
        required: true

permissions:
  contents: read

env:
  S3_LOG_EXTRACTION_PASSWORD: ${{ secrets.S3_LOG_EXTRACTION_PASSWORD }}
  MAXMIND_ACCOUNT_ID: ${{ secrets.MAXMIND_ACCOUNT_ID }}
  MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}

jobs:

  run:
    # Will read on PR dashboard as 'Deploy / RemoteTests / ubuntu'
    # Action dashboard identified by 'Remote testing'
    # Requirement settings identified as 'RemoteTests / ubuntu'
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Global Setup
        run: python -m pip install -U pip

      - name: Install local checkout
        run: pip install --no-cache-dir .[all] --group all

      - name: Display installed packages and their sources for debugging
        run: pip list

      - name: Ensure caching is working
        run: ls ~

      - name: Cache the GeoLite2 database and IP to region mapping to avoid re-downloading
        uses: actions/cache@v6
        id: enable_cache
        with:
          path: ~/.s3_log_extraction
          key: ubuntu_home_cache

      - if: steps.enable_cache.outputs.cache-hit == 'true'
        name: Ensure caching is working
        run: |
          ls ~
          ls ~/.s3_log_extraction
          cat ~/.s3_log_extraction/ip_hash_to_region.yaml

      - name: Run pytest with coverage and printout coverage for debugging
        run: pytest -m "remote" -vv -rsx --cov=s3_log_extraction --cov-report xml:./coverage.xml

      - name: Printout coverage for debugging
        run: cat ./coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_CREDENTIALS }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
